### ISSUE TITLE
[DOCKER] recipe for target 'serve' failed

### ISSUE THREAD

**Issue by tillmannschatz** [ReceiptManager/receipt-parser-server#24]
Hi,

I tried to run the docker container 
`docker run -p 192.168.178.7:8721:8721  monolidth/receipt-parser`

and got the following error message:
```
python src/receipt_server.py
Traceback (most recent call last):
  File "src/receipt_server.py", line 10, in <module>
    from fastapi import FastAPI, Depends, UploadFile, File, Security, HTTPException
  File "/usr/local/lib/python3.6/dist-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/local/lib/python3.6/dist-packages/fastapi/applications.py", line 18, in <module>
    from fastapi.openapi.utils import get_openapi
  File "/usr/local/lib/python3.6/dist-packages/fastapi/openapi/utils.py", line 17, in <module>
    from fastapi.responses import Response
  File "/usr/local/lib/python3.6/dist-packages/fastapi/responses.py", line 10, in <module>
    from starlette.responses import UJSONResponse as UJSONResponse  # noqa
ImportError: cannot import name 'UJSONResponse'
make: *** [serve] Error 1
Makefile:13: recipe for target 'serve' failed
```

### Environment info
Hardware:
```
Intel NUC Kit NUC7I5BNHX1
Running Proxmox VE 6.3-3
Intel Core i5-7260U Processor
VM Settings for Processor: Host

```
Operating System:
```
$ uname -a ; lsb_release -a
Linux ReceiptManager 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

Docker:
```
$ docker --version
Docker version 20.10.1, build 831ebea
```

**Comment by monolidth** [comment]
You tried the official docker image? Or did you build this image by your own?
Regards,
William

**Comment by tillmannschatz** [comment]
I did a fresh VM setup, just to be sure to be able to reproduce the error.

I pulled the image from dockerhub:
```
$ docker pull monolidth/receipt-parser:latest
latest: Pulling from monolidth/receipt-parser
5bed26d33875: Pull complete
f11b29a9c730: Pull complete
930bda195c84: Pull complete
78bf9a5ad49e: Pull complete
84227541b6bb: Pull complete
4f31c9672ae8: Pull complete
3ab00ff69975: Pull complete
ba1f9a4960a4: Pull complete
1e2e9ebd327e: Pull complete
5dbeace46811: Pull complete
236b4193378a: Pull complete
b9f9bf63f61e: Pull complete
2eb51bb0841b: Pull complete
4f82ba6678f4: Pull complete
07b7065a6f61: Pull complete
493d4ba34fc4: Pull complete
32a3e6a97b18: Pull complete
b06aaa810eda: Pull complete
3d3ab0f4d19c: Pull complete
ea7acb71e530: Pull complete
9f2868193fdf: Pull complete
Digest: sha256:8e9c5b696f40922052960bbebe4cb2552ecebcb613f1281e5d8dc1efb70bb1f1
Status: Downloaded newer image for monolidth/receipt-parser:latest
docker.io/monolidth/receipt-parser:latest
```

And tried to run it:
```
$ docker run -p 192.168.178.7:8721:8721  monolidth/receipt-parser
python src/receipt_server.py
Traceback (most recent call last):
  File "src/receipt_server.py", line 10, in <module>
    from fastapi import FastAPI, Depends, UploadFile, File, Security, HTTPException
  File "/usr/local/lib/python3.6/dist-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/local/lib/python3.6/dist-packages/fastapi/applications.py", line 18, in <module>
    from fastapi.openapi.utils import get_openapi
  File "/usr/local/lib/python3.6/dist-packages/fastapi/openapi/utils.py", line 17, in <module>
    from fastapi.responses import Response
  File "/usr/local/lib/python3.6/dist-packages/fastapi/responses.py", line 10, in <module>
    from starlette.responses import UJSONResponse as UJSONResponse  # noqa
ImportError: cannot import name 'UJSONResponse'
make: *** [serve] Error 1
Makefile:13: recipe for target 'serve' failed
```

Maybe it's a dependency problem of starlette / is the starlette version in the `requirements.txt` correct?


Thanks for the feedback and a happy new year
Tillmann

**Comment by tillmannschatz** [comment]
Hi,

I also did try your recommended install path from your [wiki](https://github.com/ReceiptManager/receipt-parser-server/wiki/Recommended-install-guide):

System preparation:
```
$ sudo apt install python3 python3-venv python3-pip
$ sudo apt install virtualenv python3-virtualenv
$ sudo apt-get install libmagickwand-dev
```

Git clone:
```
$ git clone https://github.com/ReceiptManager/receipt-parser-server
```

Dependencies installation:
```
$ cd receipt-parser-server/
$ pip3 install -r requirements.txt

```

Here I receive the message that I've a version conflict in starlette:
```
fastapi 0.63.0 has requirement starlette==0.13.6, but you'll have starlette 0.14.1 which is incompatible.
```

Certificate creation:
```
$ echo "mySuperSafePasswordWithNumbers12345.32!" > .private_key
$ make generate_cert
```

Running the server:
```
$ make serve
```
Generates the error (I guess it's due to running the receipt_server.py with python2):
```
$ make serve
python src/receipt_server.py
  File "src/receipt_server.py", line 65
    async def get_api_key(
            ^
SyntaxError: invalid syntax
make: *** [Makefile:13: serve] Error 1
```

Changing line 14 in `Makefile`  to: `python3 src/receipt_server.py`
And running the server again generates the same error message as with the Docker Container:
```
$ make serve
python3 src/receipt_server.py
Traceback (most recent call last):
  File "src/receipt_server.py", line 10, in <module>
    from fastapi import FastAPI, Depends, UploadFile, File, Security, HTTPException
  File "/home/me/.local/lib/python3.7/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/home/me/.local/lib/python3.7/site-packages/fastapi/applications.py", line 18, in <module>
    from fastapi.openapi.utils import get_openapi
  File "/home/me/.local/lib/python3.7/site-packages/fastapi/openapi/utils.py", line 17, in <module>
    from fastapi.responses import Response
  File "/home/me/.local/lib/python3.7/site-packages/fastapi/responses.py", line 10, in <module>
    from starlette.responses import UJSONResponse as UJSONResponse  # noqa
ImportError: cannot import name 'UJSONResponse' from 'starlette.responses' (/home/me/.local/lib/python3.7/site-packages/starlette/responses.py)
make: *** [Makefile:13: serve] Error 1
```

**Comment by monolidth** [comment]
Looks like the commit b0146c9 is broken. The UJSONResponse package is remove in newer starlette versions according to Github. Installing `starlette==0.13.6` should do the job. I will ignore automatically package updates on this package.

```
pip install starlette==0.13.6
```

**Comment by monolidth** [comment]
Should be fixed in commit 18d7ad8. Could you please confirm this?

**Comment by tillmannschatz** [comment]
Yes, it works now!

**Comment by monolidth** [comment]
If you have any issues, please let me know. I correct the `JSON` response because I switched from FLASK to FASTAPI due a massive performance boost.

You can find the latest changes in 1a75f0f290991588a304f568f349ed963c8def69.
* update your Docker container and you would be good to go!

Regards,
William
